#!/bin/sh

# Determining the directory where xkeen is located
script_dir="$(cd "$(dirname "$0")" && pwd)"

# Hiding the main xkeen directory
install_xkeen_rename() {
    source_dir="_xkeen"
    target_dir=".xkeen"
    source_path="$script_dir/$source_dir"
    target_path="$script_dir/$target_dir"

    if [ -d "$source_path" ]; then
        if [ -d "$target_path" ]; then
            rm -rf "$target_path" 2>/dev/null
        fi
        mv "$source_path" "$target_path"
    fi
    rm /opt/root/install.sh 2>/dev/null
}
install_xkeen_rename

add_chmod_init() {
    chmod +x $initd_dir/S99xkeen
}

# Importing modules
. "$script_dir/.xkeen/import.sh"
	
xkeen_info() {
    opkg update >/dev/null 2>&1
    opkg upgrade >/dev/null 2>&1
    # Checking the installation of packages
    info_packages

    # Collecting the necessary information about the processor
    info_cpu

    # Checking the Xray installation
    info_xray

    # Checking the Mihomo installation
    info_mihomo

    # Checking installed GeoSite databases
    info_geosite

    # Checking installed GeoiIP databases
    info_geoip

    # Checking the auto update status
    info_cron

    # Checking the XKeen version
    info_version_xkeen

    # Checking the relevance of XKeen
    info_compare_xkeen

    # Checking the Xray version
    info_version_xray

    # Checking the version of Mihomo and Yq
    info_version_mihomo
    info_version_yq

    # Installing missing packages
    install_packages
}

case "$1" in

    -i|-install)    # Starting a full installation cycle
        . "$script_dir/.xkeen/import.sh"
        clear
        echo
        check_keen_mode
        if [ -n "$keen_mode" ]; then
        echo -e "${red}Error${reset}: Installation of XKeen is only possible on Keenetic in ${green}router${reset} mode"
            exit 1
        fi
        echo -e "Running the full installation cycle ${yellow}XKeen${reset}"

        xkeen_info
        logs_cpu_info_console
        if [ -z "$architecture" ]; then
            exit 1
        fi

        tests_entware_storage
        preinstall_warn

        choice_add_proxy_cores

        if [ "$add_xray" = "true" ]; then
            clear
            echo
            download_xray
        else
            command -v xray >/dev/null 2>&1 || bypass_xray="true"
        fi

        if [ -z $bypass_xray ]; then
            install_xray
            xray_installed="installed"

            clear
            # Installing GeoSite
            choice_geosite

            delete_geosite

            install_geosite
            sleep 2

            clear
            # Installing GeoIP
            choice_geoip

            delete_geoip

            install_geoip
            sleep 2

            clear
            # Setting up automatic updates
            info_cron
            choice_update_cron
            update_cron_geofile_task
            clear
            choice_cron_time

            install_cron

            clear
            echo
            install_configs

            # Create init for cron
            $initd_dir/S05crond stop >/dev/null 2>&1
            [ -e "$initd_dir/S05crond" ] && rm -f "$initd_dir/S05crond"
            register_cron_initd
            $initd_dir/S05crond start >/dev/null 2>&1

            info_version_xray
            delete_register_xray

            echo -e "Registration in progress ${yellow}Xray${reset}"
            register_xray_list
            logs_register_xray_list_info_console

            register_xray_control
            logs_register_xray_control_info_console

            register_xray_status
            logs_register_xray_status_info_console
            sleep 2
        fi

        if [ "$add_mihomo" = "true" ]; then
            clear
            echo
            download_mihomo
        else
            command -v mihomo >/dev/null 2>&1 || bypass_mihomo="true"
        fi

        if [ -z $bypass_mihomo ]; then
            install_mihomo
            mihomo_installed="installed"
            info_version_mihomo
            info_version_yq
            add_mihomo_config
            delete_register_mihomo
            echo
            echo -e "Registration in progress ${yellow}Mihomo${reset}"
            register_mihomo_list
            logs_register_mihomo_list_info_console
            register_mihomo_control
            logs_register_mihomo_control_info_console
            register_mihomo_status
            logs_register_mihomo_status_info_console
            register_yq_list
            logs_register_yq_list_info_console
            register_yq_control
            logs_register_yq_control_info_console
            register_yq_status
            logs_register_yq_status_info_console
            sleep 2
        fi

        if [ "$xray_installed" = "installed" ] || [ "$mihomo_installed" = "installed" ]; then
            delete_register_xkeen
            clear
            echo
            echo -e "Registration in progress ${yellow}XKeen${reset}"
            register_xkeen_list
            logs_register_xkeen_list_info_console

            register_xkeen_control
            logs_register_xkeen_control_info_console

            register_xkeen_status
            logs_register_xkeen_status_info_console

            fixed_register_packages

            register_xkeen_initd
            create_xkeen_cfg
            sleep 2

            clear
            choice_autostart_xkeen
            add_chmod_init
        fi

        if [ "$xray_installed" != "installed" ] && [ "$mihomo_installed" = "installed" ]; then
            if [ -f "$install_dir/mihomo" ] && [ -f "$install_dir/yq" ] && grep -q 'name_client="xray"' $initd_dir/S99xkeen; then
                sed -i 's/name_client="xray"/name_client="mihomo"/' $initd_dir/S99xkeen
                add_chmod_init
            fi
        elif  [ "$xray_installed" = "installed" ] && [ "$mihomo_installed" != "installed" ]; then
            if [ -f "$install_dir/xray" ] && grep -q 'name_client="mihomo"' $initd_dir/S99xkeen; then
                sed -i 's/name_client="mihomo"/name_client="xray"/' $initd_dir/S99xkeen
                add_chmod_init
            fi
        fi

        # Deleting temporary files
        delete_tmp
        rm -f "$install_dir/xray_bak" "$install_dir/mihomo_bak"
        rm -rf "$xtmp_dir" "$mtmp_dir"
        sleep 2

        clear
        echo

        if [ "$xray_installed" != "installed" ] && [ "$mihomo_installed" != "installed" ]; then
            echo -e "${red}Cannot install ${reset} XKeen without proxy kernel"
            exit 1
        else
            echo -e "${green}XKeen installation completed!${reset}"
        fi
        echo

        if [ "$xray_installed" = "installed" ] || [ "$mihomo_installed" = "installed" ]; then
            if grep -q 'name_client="xray"' $initd_dir/S99xkeen; then
                echo -e "1. Set up Xray configuration along the path'${yellow}$install_conf_dir/${reset}'"
                echo -e "2. Start XKeen with the command ${yellow}xkeen -start${reset}"
                echo -e "  3. ${green}Enjoy!${reset}"
                echo
            elif grep -q 'name_client="mihomo"' $initd_dir/S99xkeen; then
                echo -e "1. Set up Mihomo configuration in the file'${yellow}$mihomo_conf_dir/config.yaml${reset}'"
                echo -e "2. Start XKeen with the command ${yellow}xkeen -start${reset}"
                echo -e "  3. ${green}Enjoy!${reset}"
                echo
            fi
        fi

        if [ "$xray_installed" = "installed" ] && [ "$mihomo_installed" = "installed" ]; then
            if grep -q 'name_client="xray"' $initd_dir/S99xkeen; then
                echo -e "If you want to switch XKeen to the kernel ${yellow}Mihomo${reset}"
                echo
                echo -e "1. Set up Mihomo configuration in the file'${yellow}$mihomo_conf_dir/config.yaml${reset}'"
                echo -e "2. Switch the proxy kernel with the command ${yellow}xkeen -mihomo${reset}"
                echo -e "3. Start XKeen with the command ${yellow}xkeen -start${reset}"
                echo -e "  4. ${green}Enjoy!${reset}"
            elif grep -q 'name_client="mihomo"' $initd_dir/S99xkeen; then
                echo -e "If you want to switch XKeen to the kernel ${yellow}Xray${reset}"
                echo
                echo -e "1. Set up Xray configuration along the path'${yellow}$install_conf_dir/${reset}'"
                echo -e "2. Switch the proxy kernel with the command ${yellow}xkeen -xray${reset}"
                echo -e "3. Start XKeen with the command ${yellow}xkeen -start${reset}"
                echo -e "  4. ${green}Enjoy!${reset}"
            fi
        echo
        fi

        echo -e "To display Help, run ${yellow}xkeen -h${reset}"
    ;;


    -io)    # Installation of XKeen OffLine
        clear
        echo
        check_keen_mode
        if [ -n "$keen_mode" ]; then
        echo -e "${red}Error${reset}: Installation of XKeen is only possible on Keenetic in ${green}router${reset} mode"
            exit 1
        fi
        echo "Installation of XKeen OffLine"

        info_cpu
        logs_cpu_info_console
        if [ -z "$architecture" ]; then
            exit 1
        fi

        if [ -f "$install_dir/xray" ]; then
            chmod +x $install_dir/xray
        elif [ -f "$install_dir/mihomo" ]; then
            chmod +x $install_dir/mihomo
            if [ -f "$install_dir/yq" ]; then
                chmod +x $install_dir/yq
            else
                echo -e "${red}Not found${reset} Mihomo configuration file parser - Yq"
                exit 1
            fi
        else
            clear
            echo
            echo -e "${red}Xray or mihomo proxy kernel not found${reset}"
            echo
            echo -e "  Если планируете использовать ядро xray, поместите бинарник ${yellow}xray${reset}\n  архитектуры ${green}$architecture${reset} в директорию /opt/sbin/ и начните установку снова"
            echo -e "xray downloads page: ${yellow}https://github.com/XTLS/Xray-core/releases/latest${reset}"
            echo
            echo -e "  Если планируете использовать ядро mihomo, поместите бинарники ${yellow}mihomo${reset} и ${yellow}yq${reset}\n  архитектуры ${green}$architecture${reset} в директорию /opt/sbin/ и начните установку снова"
            echo -e "mihomo download page: ${yellow}https://github.com/MetaCubeX/mihomo/releases/latest${reset}"
            echo -e "Yq downloads page: ${yellow}https://github.com/mikefarah/yq/releases/latest${reset}"
            echo
            exit 1
        fi

        if [ -f "$install_dir/xray" ]; then
            install_configs
    
            if [ ! -d "$geo_dir" ]; then
                mkdir -p "$geo_dir"
            fi

            clear
            delete_register_xray
            echo
            echo -e "Registration in progress ${yellow}Xray${reset}"
            register_xray_list
            logs_register_xray_list_info_console

            register_xray_control
            logs_register_xray_control_info_console

            register_xray_status
            logs_register_xray_status_info_console

            if [ -f "$install_dir/xray" ]; then
                chmod +x $install_dir/xray
            fi
        fi

        if [ -f "$install_dir/mihomo" ]; then
            add_mihomo_config
            delete_register_mihomo
            echo
            echo -e "Registration in progress ${yellow}Mihomo${reset}"
            register_mihomo_list
            logs_register_mihomo_list_info_console
            register_mihomo_control
            logs_register_mihomo_control_info_console
            register_mihomo_status
            logs_register_mihomo_status_info_console
            register_yq_list
            logs_register_yq_list_info_console
            register_yq_control
            logs_register_yq_control_info_console
            register_yq_status
            logs_register_yq_status_info_console
            sleep 2
        fi

        clear
        delete_register_xkeen
        echo
        echo -e "Registration in progress ${yellow}XKeen${reset}"
        register_xkeen_list
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_console

        register_xkeen_initd
        create_xkeen_cfg

        fixed_register_packages

        clear
        choice_autostart_xkeen
        add_chmod_init

        # Deleting temporary files
        delete_tmp
        sleep 2

        clear
        echo
        echo -e "${green}XKeen installation completed!${reset}"
        echo
        echo -e "To use the kernel'${yellow}$Xray${reset}'"
        echo -e "1. Place the necessary geofiles in the directory'${yellow}$geo_dir/${reset}'"
        echo -e "2. Set up Xray configuration along the path'${yellow}$install_conf_dir/${reset}'"
        echo -e "3. Start XKeen with the command ${yellow}xkeen -start${reset}"
        echo -e "  4. ${green}Enjoy!${reset}"
        echo
        echo -e "To use the kernel ${yellow}Mihomo${reset}"
        echo -e "1. Set up Mihomo configuration in the file'${yellow}$mihomo_conf_dir/config.yaml${reset}'"
        echo -e "2. Switch the proxy kernel with the command ${yellow}xkeen -mihomo${reset}"
        echo -e "3. Start XKeen with the command ${yellow}xkeen -start${reset}"
        echo -e "  4. ${green}Enjoy!${reset}"
        echo
        echo -e "To display Help, run ${yellow}xkeen -h${reset}"
    ;;


    -ug)    # Start updating GeoFile databases
        command -v xray >/dev/null 2>&1 || { echo -e "${red}Not detected${reset} Xray proxy kernel"; exit 1; }
        echo "Updating installed GeoFile databases"

        info_geosite
        info_geoip
        if 
            [ "$update_refilter_geosite" = "true" ] || \
            [ "$update_v2fly_geosite" = "true" ] || \
            [ "$update_zkeen_geosite" = "true" ] || \
            [ "$update_refilter_geoip" = "true" ] || \
            [ "$update_v2fly_geoip" = "true" ] || \
            [ "$update_zkeenip_geoip" = "true" ]; then

            install_geoip
            install_geosite

            if pidof xray >/dev/null; then
                $initd_dir/S99xkeen restart on >/dev/null 2>&1
            fi

            echo -e "Update of installed GeoFile databases ${green}completed${reset}"
        else
            echo -e "${red}Not found ${reset} GeoFile database for update"
        fi
    ;;


    -uk)    # XKeen update (auto-select Stable/Dev version)
        clear
        echo
        echo "Checking for XKeen updates"
        xkeen_info

        if [ "$xkeen_build" != "Stable" ]; then
            download_func="download_xkeen_dev"
        else
            if [ "$info_compare_xkeen" = "actual" ]; then
                echo "No XKeen updates available"
                exit 0
            else
                echo -e "Found new version of ${yellow}XKeen${reset}"
                download_func="download_xkeen"
            fi
        fi

        backup_xkeen
        $download_func
        install_xkeen

        # Restarting the script
        if grep -E "^\s*-uk_post_update\s*\)" "$0" > /dev/null; then
            exec sh "$0" -uk_post_update
        else
            . "$script_dir/.xkeen/import.sh"

            echo -e "Unregistering previous version ${yellow}XKeen${reset}"
            delete_register_xkeen
            logs_delete_register_xkeen_info_console

            echo -e "Registering a new version of ${yellow}XKeen${reset}"
            register_xkeen_list
            logs_register_xkeen_list_info_console

            register_xkeen_control
            logs_register_xkeen_control_info_console

            register_xkeen_status
            logs_register_xkeen_status_info_console

            register_cron_initd
            register_xkeen_initd
            create_xkeen_cfg
            choice_canel_cron_select=true
            update_cron_geofile_task

            fixed_register_packages
            delete_tmp

            if pidof xray >/dev/null || pidof mihomo >/dev/null ; then
                $initd_dir/S99xkeen restart on >/dev/null 2>&1
            fi

            echo -e "XKeen update ${green}done${reset}"
        fi
    ;;


    -uk_post_update)
        . "$script_dir/.xkeen/import.sh"

        echo -e "Unregistering previous version ${yellow}XKeen${reset}"
        delete_register_xkeen
        logs_delete_register_xkeen_info_console

        echo -e "Registering a new version of ${yellow}XKeen${reset}"
        register_xkeen_list
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_console

        register_cron_initd
        register_xkeen_initd
        create_xkeen_cfg
        choice_canel_cron_select=true
        update_cron_geofile_task

        fixed_register_packages
        delete_tmp

        if pidof xray >/dev/null || pidof mihomo >/dev/null ; then
            $initd_dir/S99xkeen restart on >/dev/null 2>&1
        fi

        echo -e "XKeen update ${green}done${reset}"
    ;;


    -ux)    # Updating or installing the Xray kernel
        . "/opt/sbin/.xkeen/01_info/03_info_cpu.sh"
        status_file="/opt/lib/opkg/status"
        info_cpu
        info_xray
        info_version_xray

        clear
        echo

        [ "$xray_installed" = "installed" ] && echo -e "Xray version ${yellow}$xray_current_version${reset} is installed in the router" && echo
        download_xray

        if [ -z $bypass_xray ]; then
            install_xray

            echo -e "Unregistering previous version ${yellow}Xray${reset}"
            delete_register_xray
            logs_delete_register_xray_info_console

            echo -e "Registering a new version of ${yellow}Xray${reset}"
            register_xray_list
            logs_register_xray_list_info_console

            register_xray_control
            logs_register_xray_control_info_console

            register_xray_status
            logs_register_xray_status_info_console

            sleep 2
            if pidof xray >/dev/null; then
                $initd_dir/S99xkeen restart on >/dev/null 2>&1
            fi

            echo
            echo -e "Xray core update ${green}done${reset}"
        fi

        rm -f "$install_dir/xray_bak"
        rm -rf "$xtmp_dir"
        delete_tmp
    ;;


    -um)    # Updating or installing the Mihomo kernel
        . "/opt/sbin/.xkeen/01_info/03_info_cpu.sh"
        status_file="/opt/lib/opkg/status"
        info_cpu
        info_mihomo
        info_version_mihomo

        clear
        echo

        [ "$mihomo_installed" = "installed" ] && echo -e "Mihomo version ${yellow}$mihomo_current_version${reset} is installed in the router" && echo
        download_mihomo
        info_version_mihomo
        info_version_yq

        if [ -z $bypass_mihomo ]; then
            install_mihomo

            if [ "$mihomo_installed" = "installed" ]; then
                if pidof mihomo >/dev/null; then
                    $initd_dir/S99xkeen restart on >/dev/null 2>&1
                fi
                echo
                echo -e "Kernel update ${yellow}Mihomo${reset} ${green}done${reset}"
            else
                mihomo_installed="installed"
                info_version_mihomo
                info_version_yq
                add_mihomo_config
                delete_register_mihomo
                echo
                echo -e "Registration in progress ${yellow}Mihomo${reset}"
                register_mihomo_list
                logs_register_mihomo_list_info_console
                register_mihomo_control
                logs_register_mihomo_control_info_console
                register_mihomo_status
                logs_register_mihomo_status_info_console
                register_yq_list
                logs_register_yq_list_info_console
                register_yq_control
                logs_register_yq_control_info_console
                register_yq_status
                logs_register_yq_status_info_console
                sleep 2
                clear
                echo
                echo -e "Kernel installation ${yellow}Mihomo${reset} ${green}completed${reset}"
            fi
        fi

        rm -f "$install_dir/mihomo_bak"
        rm -rf "$mtmp_dir"
        delete_tmp
    ;;


    -ugc)    # Create or modify an existing GeoFile database auto-update task
        command -v xray >/dev/null 2>&1 || { echo -e "${red}Not detected${reset} Xray proxy kernel"; exit 1; }
        info_cron
        clear
        echo -e "Creating or changing the database auto-update task ${yellow}GeoFile${reset}"
        choice_update_cron
        update_cron_geofile_task
        choice_cron_time
        install_cron
        delete_tmp
        echo -e "Creation or modification of the GeoFile database auto-update task ${green}completed${reset}"
    ;;


    -ri)    # Create XKeen startup file
        clear
        $initd_dir/S99xkeen stop >/dev/null 2>&1
        [ -e "$initd_dir/S99xkeen" ] && rm -f "$initd_dir/S99xkeen"

        echo -e "Creating an autorun file ${yellow}XKeen${reset}"
        sleep 1

        register_xkeen_initd
        logs_register_xkeen_initd_info_console

        echo
        echo -e "XKeen autorun file creation ${green}completed${reset}"
        echo -e "If the configuration is configured, you can start proxying with the command'${yellow}xkeen -start${reset}'"
    ;;


    -dgc)    # Delete the GeoFile database auto-update task
        clear
        echo
        choice_for_remove="GeoFile database auto-update task"
        choice_remove

        info_cron

        clear
        echo
        echo -e "Deleting the database auto-update task ${yellow}GeoFile${reset}"

        delete_cron_geofile
        logs_delete_cron_geofile_info_console
        delete_tmp

        echo -e "Deleting the GeoFile database auto-update task ${green}completed${reset}"
    ;;


    -dx)    # Remove Xray
        clear
        echo
        choice_for_remove="Xray"
        choice_remove
        clear
        echo
        command -v xray >/dev/null 2>&1 || { echo -e "Xray ${red}not installed${reset}"; exit 1; }
        echo -e "Removing ${yellow}Xray${reset}"

        $initd_dir/S99xkeen stop >/dev/null 2>&1
        opkg remove xray_s
        rm -f "$install_dir/xray"

        echo
        echo -e "Removing ${yellow}Xray configuration files${reset}"

        delete_configs
        logs_delete_configs_info_console

        echo
        echo -e "Xray deletion ${green}done${reset}"
    ;;


    -dm)    # Remove Mihomo
        clear
        echo
        choice_for_remove="Mihomo"
        choice_remove
        clear
        echo
        command -v mihomo >/dev/null 2>&1 || { echo -e "Mihomo ${red}not installed${reset}"; exit 1; }
        echo -e "Removing ${yellow}Mihomo${reset}"

        $initd_dir/S99xkeen stop >/dev/null 2>&1
        opkg remove mihomo_s
        opkg remove yq_s
        rm -f "$install_dir/mihomo" "$install_dir/yq"
        rm -rf "$mihomo_conf_dir"

        echo
        echo -e "Mihomo ${green}removal completed${reset}"
    ;;


    -dk)    # Remove XKeen
        clear
        echo
        choice_for_remove="XKeen"
        choice_remove

        clear
        echo
        echo -e "Removing ${yellow}XKeen${reset}"
        opkg remove xkeen
        delete_tmp

        clear
        echo
        delete_all

        clear
        echo
        echo -e "XKeen ${green} uninstall completed${reset}"
        echo
        echo -e "You can reinstall ${yellow}XKeen${reset} with the commands:"
        echo
        echo -e "  ${green}curl -OL https://raw.githubusercontent.com/jameszeroX/XKeen/main/install.sh${reset}"
        echo -e "  ${green}chmod +x install.sh${reset}"
        echo -e "  ${green}./install.sh${reset}"
    ;;


    -dgi)    # Remove GeoIP's
        clear
        echo
        choice_for_remove="GeoIP's"
        choice_remove

        clear
        echo
        echo -e "Removing all databases ${yellow}GeoIP${reset}"

        delete_geoip_key
        logs_delete_geoip_info_console

        echo
        echo -e "Deleting all GeoIP databases ${green}done${reset}"
    ;;


    -dgs)    # Remove GeoSite's
        clear
        echo
        choice_for_remove="GeoSite's"
        choice_remove

        clear
        echo
        echo -e "Removing all databases ${yellow}GeoSite${reset}"

        delete_geosite_key
        logs_delete_geosite_info_console

        echo
        echo -e "Removal of all GeoSite databases ${green}done${reset}"
    ;;


    -drx)    # Remove Xray registration
        clear
        echo
        choice_for_remove="Xray registration"
        choice_remove

        clear
        echo
        echo -e "Removing ${yellow}Xray registration${reset}"

        delete_register_xray
        logs_delete_register_xray_info_console

        echo -e "Xray registration deletion ${green}done${reset}"
    ;;


    -drm)    # Delete Mihomo registration
        clear
        echo
        choice_for_remove="Mihomo registration"
        choice_remove

        clear
        echo
        echo -e "Deleting ${yellow}Mihomo${reset} registration"

        delete_register_mihomo
        logs_delete_register_mihomo_info_console

        echo -e "Deleting Mihomo registration ${green}done${reset}"
    ;;


    -drk)    # Delete XKeen registration
        clear
        echo
        choice_for_remove="XKeen registration"
        choice_remove

        clear
        echo
        echo -e "Removing ${yellow}XKeen${reset} registration"

        delete_register_xkeen
        logs_delete_register_xkeen_info_console

        echo -e "XKeen registration deletion ${green}done${reset}"
    ;;


    -remove)    # Complete uninstallation of XKeen and all dependencies
        clear
        echo
        choice_for_remove="XKeen completely with all dependencies"
        choice_remove

        info_cron
        clear
        echo
        echo -e "Deleting the database auto-update task ${yellow}GeoFile${reset}"
        delete_cron_geofile
        logs_delete_cron_geofile_info_console

        echo
        echo -e "Deleting the GeoFile database auto-update task ${green}completed${reset}"
        sleep 2

        # Removing GeoIP's
        clear
        echo
        echo -e "Removing all databases ${yellow}GeoIP${reset}"

        delete_geoip_key
        logs_delete_geoip_info_console

        echo -e "Deleting all GeoIP databases ${green}done${reset}"
        sleep 2

        # Removing GeoSite's
        clear
        echo
        echo -e "Removing all databases ${yellow}GeoSite${reset}"

        delete_geosite_key
        logs_delete_geosite_info_console

        echo -e "Removal of all GeoSite databases ${green}done${reset}"
        sleep 2

        # Removing Xray configuration files
        clear
        echo
        echo -e "Removing ${yellow}Xray configuration files${reset}"

        delete_configs
        logs_delete_configs_info_console

        echo
        echo -e "Removing Xray configuration files ${green}done${reset}"
        sleep 2

        # Removing Xray
        clear
        echo
        echo -e "${yellow}Delete${reset} Xray"

        $initd_dir/S99xkeen stop >/dev/null 2>&1
        opkg remove xray_s
        rm -f "$install_dir/xray"
        rm -rf "/opt/etc/xray"

        echo
        echo -e "Xray deletion ${green}done${reset}"
        sleep 2

        # Removing Mihomo
        clear
        echo
        echo -e "${yellow}Delete${reset} Mihomo"
        opkg remove mihomo_s
        opkg remove yq_s
        rm -f "$install_dir/mihomo" "$install_dir/yq"
        rm -rf "$mihomo_conf_dir"

        echo
        echo -e "Mihomo ${green}removal completed${reset}"
        sleep 2

        # Removing XKeen
        clear
        echo
        echo -e "Removing ${yellow}XKeen${reset}"
        opkg remove xkeen
        delete_tmp

        clear
        echo
        delete_all

        clear
        echo
        echo -e "Complete uninstallation of ${yellow}XKeen${reset} and all ${green} dependencies completed${reset}"
        echo
        echo -e "You can reinstall ${yellow}XKeen${reset} with the commands:"
        echo
        echo -e "  ${green}curl -OL https://raw.githubusercontent.com/jameszeroX/XKeen/main/install.sh${reset}"
        echo -e "  ${green}chmod +x install.sh${reset}"
        echo -e "  ${green}./install.sh${reset}"
    ;;


    -rrk)    # Update XKeen registration
        clear
        echo -e "Registration update ${yellow}XKeen${reset}"

        info_cpu
        info_version_xkeen

        delete_register_xkeen    
        logs_delete_register_xkeen_info_console

        register_xkeen_list
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_console

        echo
        echo -e "XKeen registration update in system ${green}completed${reset}"
    ;;


    -rrx)    # Update Xray registration
        command -v xray >/dev/null 2>&1 || { echo -e "${red}Not detected${reset} Xray proxy kernel"; exit 1; }
        clear
        echo -e "Registration update ${yellow}Xray${reset}"

        info_xray
        info_cpu
        info_version_xray

        delete_register_xray
        logs_delete_register_xray_info_console

        register_xray_list
        logs_register_xray_list_info_console

        register_xray_control
        logs_register_xray_control_info_console

        register_xray_status
        logs_register_xray_status_info_console

        echo
        echo -e "Xray registration update ${green}completed${reset}"
    ;;


    -rrm)    # Update Mihomo registration
        command -v mihomo >/dev/null 2>&1 || { echo -e "${red}Not detected${reset} Mihomo proxy kernel"; exit 1; }
        clear
        echo -e "Registration update ${yellow}Mihomo${reset}"

        info_mihomo
        info_cpu
        info_version_mihomo
        info_version_yq

        delete_register_mihomo
        logs_delete_register_mihomo_info_console

        register_mihomo_list
        logs_register_mihomo_list_info_console

        register_mihomo_control
        logs_register_mihomo_control_info_console

        register_mihomo_status
        logs_register_mihomo_status_info_console

        register_yq_list
        logs_register_yq_list_info_console

        register_yq_control
        logs_register_yq_control_info_console

        register_yq_status
        logs_register_yq_status_info_console

        echo
        echo -e "Mihomo registration update in ${green}system completed${reset}"
    ;;


    -k)    # Reinstalling XKeen
        . "/opt/sbin/.xkeen/01_info/03_info_cpu.sh"
        status_file="/opt/lib/opkg/status"
        info_cpu
        xkeen_info

        clear
        echo -e "Reinstalling ${yellow}XKeen${reset}"

        choice_redownload_xkeen
        if [ -n "$redownload_xkeen" ]; then
            if [ "$xkeen_build" = "Stable" ]; then
                download_func="download_xkeen"
            else
                download_func="download_xkeen_dev"
            fi
            $download_func
        fi

        echo
        install_xkeen

        # Restarting the script
        if grep -E "^\s*-k_post_install\s*\)" "$0" > /dev/null; then
            exec sh "$0" -k_post_install
        else
            . "$script_dir/.xkeen/import.sh"
            echo -e "Unregistering previous version ${yellow}XKeen${reset}"
            delete_register_xkeen
            logs_delete_register_xkeen_info_console

            echo -e "Registering a new version of ${yellow}XKeen${reset}"
            register_xkeen_list
            logs_register_xkeen_list_info_console

            register_xkeen_control
            logs_register_xkeen_control_info_console

            register_xkeen_status
            logs_register_xkeen_status_info_console

            register_cron_initd
            register_xkeen_initd
            create_xkeen_cfg
            choice_canel_cron_select=true
            update_cron_geofile_task

            fixed_register_packages
            delete_tmp

            if pidof xray >/dev/null || pidof mihomo >/dev/null ; then
                $initd_dir/S99xkeen restart on >/dev/null 2>&1
            fi

            echo
            echo -e "Reinstallation of XKeen ${green}completed${reset}"
        fi
    ;;


    -k_post_install)
        . "$script_dir/.xkeen/import.sh"
        echo -e "Unregistering previous version ${yellow}XKeen${reset}"
        delete_register_xkeen
        logs_delete_register_xkeen_info_console

        echo -e "Registering a new version of ${yellow}XKeen${reset}"
        register_xkeen_list
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_console

        register_cron_initd
        register_xkeen_initd
        create_xkeen_cfg
        choice_canel_cron_select=true
        update_cron_geofile_task

        fixed_register_packages
        delete_tmp

        if pidof xray >/dev/null || pidof mihomo >/dev/null ; then
            $initd_dir/S99xkeen restart on >/dev/null 2>&1
        fi

        echo
        echo -e "Reinstallation of XKeen ${green}completed${reset}"
    ;;


    -g)    # Reinstalling GeoFile databases
        command -v xray >/dev/null 2>&1 || { echo -e "${red}Not detected${reset} Xray proxy kernel"; exit 1; }
        clear
        info_geosite
        info_geoip

        choice_geosite
        delete_geosite
        install_geosite
        sleep 2

        clear
        choice_geoip
        delete_geoip
        install_geoip
        sleep 2

        clear
        echo
        echo -e "Reinstallation of GeoFile databases ${green}completed${reset}"
    ;;


    -kb)    # Backup XKeen
        echo -e "Creating a backup ${yellow}XKeen${reset}"
        info_version_xkeen
        backup_xkeen
    ;;


    -kbr)    # Restoring XKeen from a backup
        echo -e "Restoring ${yellow}XKeen${reset} from a backup"
        restore_backup_xkeen
    ;;


    -cb)    # Backup Xray Configuration
        command -v xray >/dev/null 2>&1 || { echo -e "${red}Not detected${reset} Xray proxy kernel"; exit 1; }
        echo -e "Backing up ${yellow}Xray configuration ${reset}"
        backup_configs_xray
    ;;


    -cbr)    # Restoring an Xray configuration from a backup
        command -v xray >/dev/null 2>&1 || { echo -e "${red}Not detected${reset} Xray proxy kernel"; exit 1; }
        echo -e "Restoring ${yellow}Xray${reset} configuration from backup"
        restore_backup_configs_xray
    ;;


    -mb)    # Mihomo Configuration Backup
        echo -e "Backing up ${yellow}Mihomo${reset} configuration"
        backup_configs_mihomo
    ;;


    -mbr)    # Restoring Mihomo configuration from a backup
        echo -e "Restoring ${yellow}Mihomo${reset} configuration from backup"
        restore_backup_configs_mihomo
    ;;


    -tc)    # Connection test
        echo "Checking your Internet connection"
        tests_connection
        echo -e "Internet connection check ${green}completed${reset}"
    ;;


    -tpx)    # Show listening ports
        echo "Defining listening ports"
        tests_ports_client
    ;;


    -tfk)    # Check XKeen files
        echo -e "Checking files ${yellow}XKeen${reset}"
        echo -e "XKeen files check ${green}completed${reset}"
    ;;


    -tfx)    # Check Xray files
        echo -e "Checking files ${yellow}Xray${reset}"
        echo -e "Xray files check ${green}completed${reset}"
    ;;


    -v)    # Show XKeen version
        echo "Версия XKeen $xkeen_current_version $xkeen_build"
    ;;


    -about)    # About the program
        clear
        about_xkeen
    ;;


    -ad)    # Support developers
        clear
        author_donate
    ;;


    -af)    # Feedback
        clear
        author_feedback
    ;;


    -h)    # Help
        clear
        help_xkeen
    ;;


    -start)    # Launch of XKeen
        add_chmod_init
        $initd_dir/S99xkeen start on
        ip route flush cache
    ;;


    -stop)    # Stop XKeen
        add_chmod_init
        $initd_dir/S99xkeen stop
    ;;


    -restart)    # Restart XKeen
        add_chmod_init
        $initd_dir/S99xkeen restart on
    ;;


    -status)    # XKeen status
        $initd_dir/S99xkeen status
    ;;


    -auto)    # Changing XKeen launch mode
        change_autostart_xkeen
        add_chmod_init
    ;;


    -fd)    # Changing the file descriptor control mode
        if grep -q 'check_fd="on"' $initd_dir/S99xkeen; then
            sed -i 's/check_fd="on"/check_fd="off"/' $initd_dir/S99xkeen
            echo -e "Control of file descriptors opened by the proxy client ${red}disabled${reset}. ${yellow}Reboot your router!${reset}"
        else
            sed -i 's/check_fd="off"/check_fd="on"/' $initd_dir/S99xkeen
            echo -e "Control of file descriptors opened by the proxy client ${green}enabled${reset}. ${yellow}Reboot your router!${reset}"
        fi
        add_chmod_init
    ;;


    -ap)    # Add proxy port
        shift
        add_ports_donor "$*"
        sleep 2
        add_chmod_init
        if pidof xray >/dev/null || pidof mihomo >/dev/null ; then
            $initd_dir/S99xkeen restart on >/dev/null 2>&1
        fi
    ;;


    -dp)    # Remove proxy port
        shift
        dell_ports_donor "$*"
        sleep 2
        add_chmod_init
        if pidof xray >/dev/null || pidof mihomo >/dev/null ; then
            $initd_dir/S99xkeen restart on >/dev/null 2>&1
        fi
    ;;


    -cp)    # Get a list of proxy ports
        get_ports_donor
    ;;


    -ape)    # Add proxy exception port
        shift
        add_ports_exclude "$*" 
        sleep 2
        add_chmod_init
        if pidof xray >/dev/null || pidof mihomo >/dev/null ; then
            $initd_dir/S99xkeen restart on >/dev/null 2>&1
        fi
    ;;


    -dpe)    # Remove proxy exclusion port
        shift
        dell_ports_exclude "$*"
        sleep 2
        add_chmod_init
        if pidof xray >/dev/null || pidof mihomo >/dev/null ; then
            $initd_dir/S99xkeen restart on >/dev/null 2>&1
        fi
    ;;


    -cpe)    # Get a list of ports excluded from proxying
        get_ports_exclude
    ;;


    -modules)    # Transferring the necessary modules from the firmware to the user directory
        clear
        echo
        keenos_modules
        migration_modules
    ;;

    -delmodules)    # Removing modules from a user directory
        clear
        echo
        keenos_modules
        remove_modules
    ;;


    -d)    # Setting the autostart delay in seconds
        shift
        delay_autostart "$1"
        sleep 2
        add_chmod_init
    ;;


    -diag)    # XKeen Diagnostics
        tests_entware_storage
        clear
        diagnostic
    ;;


    -channel)    # Changing the XKeen update channel (Stable/Dev)
        clear
        choice_channel_xkeen
        change_channel_xkeen

    ;;


    -xray)    # Changing the proxy kernel to Xray
        choice_xray_core
    ;;


    -mihomo)    # Changing the proxy kernel to Mihomo
        choice_mihomo_core
    ;;


    *)
        echo -e "Unknown key: ${red}$1${reset}"
        echo -e "List of available keys: ${yellow}xkeen -h${reset}"
    ;;
esac
